import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/style/globals.css";
import ThemeProvider from '@/context/ThemeContext';
import Navbar from '@/components/Navbar/Navbar';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import ScrollTop from '@/components/config/ScrollTop';

const poppins = Poppins({weight: ['300', '500', '700'], subsets: ['latin']})

export const metadata: Metadata = {
  title: "Fabio Estevez Developer",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale:string}
}>) {
  const messages = useMessages()
  return (
    <html lang={locale}>
      <body className={`${poppins.className} max-w-screen-2xl m-auto relative scroll-smooth`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider>
            <Navbar/>
            {children}
            <ScrollTop/>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
